---

name: 'dbsql_dbt_tpch'
version: '1.0.0'
config-version: 2

profile: 'sql_endpoints'

vars:
  # tpcdi_directory: /Volumes/tpcdi/tpcdi_raw_data/tpcdi_volume/
  tpcdi_directory: UC_WESTUS_TPCDI_FILES/sf=10/
  scalefactor: 10
  benchmark: 10
  stage: stagename
  stagingcatalog: main
  stagingschema: tpcdi_staging
  bucketname: bucketname  # bigquery, redshift only
  storageaccountname: synapsemigrationdemoadls
  catalog: main
  prodschema: dbtpcdi_prod

# model-paths: ["Databricks/models/main"]
model-paths: ["Snowflake/models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbsql_dbt_tpch', 'dbt_utils']
